mjfreelancer/login/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.home, name ='home'),
    url(r'^freelancer/$', views.freelancer_home, name='freelancer_home'),
    url(r'^cadastro/$', views.cadastro , name='cadastro'),
    url(r'^contato/$', views.contato , name='contato'),

    #url(r'^contato/(?P<pk>[0-9]+)/$', views.contato_detail), url(r'^contato/new/$', views.new_contato, name='new_contato'),

]

mjfreelancer/urls.py
from django.conf.urls import include, url 
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    # Examples:
    # url(r'^$', 'mjfreelancer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('mjfreelancer.login.urls')),
   

]

if settings.DEBUG:
	urlpatterns == static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mjfreelancer/login/models.py
from django.db import models
from django.utils import timezone
class Login(models.Model):
	login_email = models.CharField(verbose_name = "Email ", max_length = 50)
	login_senha = models.CharField(verbose_name = "Senha ",  max_length = 30)


class Contato(models.Model):

	

	Email = models.CharField(verbose_name = "Email ", max_length = 50)
	data = models.CharField(verbose_name = "Data ", max_length = 20)
	nome = models.CharField(verbose_name = "Nome ", max_length = 50)
	mensagem = models.CharField(verbose_name = "mensagem ", max_length=500)

# Create your models here.
class Cliente(models.Model):	
	Nome = models.CharField(max_length=70, blank=True)
	Email = models.EmailField(max_length=30, blank=True)
	Foto = models.CharField(max_length=100, null=True)
	Senha = models.CharField(max_length=30, blank=True)
	Telefone = models.IntegerField(blank=True,null=True)


class PessoaFisica(models.Model):
	CPF = models.IntegerField(blank=True, primary_key=True)
	fk_idCliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)

class PessoaJuridica(models.Model):
	CNPJ = models.IntegerField(blank=True, primary_key=True)
	Cliente =  models.ForeignKey('Cliente', on_delete=models.CASCADE)

class Freelancer(models.Model):
	Nome = models.CharField(max_length=70, blank=True)
	Email = models.EmailField(max_length=20, blank=True)
	Endereco = models.CharField(max_length=100, blank=True)
	Cidade = models.CharField(max_length=30, blank=True)
	Estado = models.CharField(max_length=20, blank=True)
	CPF = models.CharField(max_length=11, blank=True, unique=True)
	Agencia = models.CharField(max_length=6, blank=True)
	Banco = models.CharField(max_length=25, blank=True)
	Conta = models.CharField(max_length=10, blank=True)
	Telefone = models.CharField(max_length=10, blank=True)
	Senha = models.CharField(max_length=25, blank=True)
	Especialidade = models.CharField(max_length=150)
	SobreMim = models.CharField(max_length=150)
	NotaAvaliativa = models.IntegerField()
	Foto = models.CharField(max_length=100, null=True)

class Projeto(models.Model):
	Nome = models.CharField(max_length=70, blank=True)
	AreaProjeto =  models.CharField(max_length=70, blank=True)
	DataPublicacao = models.DateTimeField(blank=True, null=True)
	DataInicio = models.DateTimeField(blank=True, null=True)
	DataFim = models.DateTimeField(blank=True, null = True)
	Preco = models.FloatField(blank=True, null=True)
	Descricao = models.CharField(max_length=200, blank=True)
	cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE,default=1)
	idFreelancer = models.ForeignKey(Freelancer, on_delete=models.CASCADE,default=1)

class Interessados_Projeto(object):
	fk_idFreelancer = models.ForeignKey('Freelancer', on_delete=models.CASCADE, primary_key=True,default=1)
	fk_idProjeto = models.ForeignKey('Projeto', on_delete=models.CASCADE, primary_key=True,default=1)

# Create your models here.

mjfreelancer/login/forms.py
from django import forms
from .models import Login
from .models import Contato
from .models import Freelancer
from .models import Cliente, PessoaFisica, PessoaJuridica
#forms.CharField(label="", widget = forms.passwordInput())
class LoginForm(forms.ModelForm):	
	class Meta:
		model = Login
		fields = ['login_email', 'login_senha']

class contatoForm(forms.ModelForm):	
	class Meta:
		model = Contato
		fields = ['nome','data','Email', 'mensagem']
class FreelancerForm(forms.ModelForm):

	class Meta:
		model = Freelancer
		fields = ['Nome','Email','CPF','Endereco','Cidade','Estado','Agencia','Banco','Conta','Telefone','Senha','Especialidade','SobreMim']

class ClienteForm(forms.ModelForm):
	class Meta:
		model = Cliente
		fields = ['Nome','Email','Senha','Telefone']
class PessoaFisicaForm(forms.ModelForm):
	class Meta:
		model = PessoaFisica
		fields = ['CPF']
class PessoaJuridicaForm(forms.ModelForm):
	class Meta:
		model = PessoaJuridica
		fields = ['CNPJ']

mjfreelancer/login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import contatoForm, LoginForm, FreelancerForm, PessoaFisicaForm, PessoaJuridicaForm, ClienteForm
from .models import Login, Contato, Freelancer, PessoaFisica, PessoaJuridica, Cliente
from django.template import Context, loader
####
#class Session():
#	def __init__ (self):
#		self.ativo= False
##	def setAtivo(self, ativo):
#		self.ativo = ativo
#	def getAtivo(self):
#		return self.ativo

def freelancer_home(request):

	if(True):
		context = {
			"nome": "Wildyson"
		}
		return render(request,'login/freelancer.html', context)
	return redirect('home')

def cadastro(request):
	
	context = {
		"nome": "aloo"
	}
	
	if(request.method == 'POST'):
		if(request.POST.get('selectbasic', False) == "1"):
			form = FreelancerForm(request.POST) 
			if form.is_valid():
				instance = form.save(commit=False)
				instance.NotaAvaliativa = 0
				print(instance.Email)
				instance.save()
				print("valido")
				return HttpResponse(" DADOS CADASTRADOS")
			else:
				print form.errors, len(form.errors)
				print("invalido")
		else:
			form = ClienteForm(request.POST)
			if form.is_valid():
				instance = form.save(commit=False)
				instance.save()
				print("valido")
				return HttpResponse(" DADOS CADASTRADOS")
			else:
				print form.errors, len(form.errors)
				print("invalido")

		
	return render(request,'login/cadastro.html', context)

def contato(request):
	form = contatoForm(request.POST)
	if(request.method == 'POST'):
		if form.is_valid():  
			form.save()
			return HttpResponse("Mensagem Enviada")
		else:
			print("Formulario nao e valido")
			print form.errors, len(form.errors)
	return render(request,'login/contato.html', {})
	
def home(request):
	title = ""
	freelancer= Freelancer.objects.all()

	form = LoginForm(request.POST)
	context = {
		"form": form,
		"title": title
	}
	if(request.method == 'POST'):	
		if form.is_valid():
			instance = form.save(commit=False)
			for f in freelancer:
				#print(lg.login_email)
				if ((instance.login_email == f.Email) and (instance.login_senha == f.Senha)):
					#instance.save()
					context = {
						"title": "Login Efetuado"
					}
					
					return redirect('freelancer_home')
			context = {
				"form": form,
				"title": "Login Invalido"
			}
	return render(request,'login/index.html', context )

# Create your views here.

mjfreelancer/templates/login/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Django Freelancers</title>
        <link rel="stylesheet" href="{% static 'estilos/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'estilos/bootstrap.min.css' %}">
        
        
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'new_contato' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">Majuca Freelancers</a></h1>
        </div>
        <div>
            
           {% block content %}

           {% endblock %}
        </div>
    </body>
</html>

mjfreelancer/templates/login/cadastro.html
{% load staticfiles %}

<!DOCTYPE html>
	<head>
		<title> Cadastro </title>
		
		<link rel="stylesheet" href="{% static 'estilos/cadastro.css' %}">
		<link rel="stylesheet" href="{% static 'estilos/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'estilos/bootstrap.min.css' %}">
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>	
		<script src="{% static 'js/cadastrojs.js' %}" type="text/javascript" ></script>	
		
	    
	</head>
	<body>

		<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a  class="navbar-brand" style="color: #32CD32"  href="/">Majuca Freelancers</a>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav mr-auto">    	
			    </ul>
			    <div>
				</div>

			</div>
		</nav>

		
		<form  method="post" action="" class="form-horizontal">
		 {% csrf_token %} 
			<fieldset>
			

		<!-- Form Name -->
				<legend style="background-color: #F5DEB3">Cadastro de Usuario<br> <h6>Os campos que contem <h11>*</h11> são obrigatorios </h6></legend>

		<!-- Multiple Radios (inline) -->
				<div class="container-fluid" style="background-color: #F5F5DC">
					<div class="container" style="left: 200px;">
						
						<!-- Text input-->
						<div  class="form-group">

							<div class="row">
						 		 <label class="col-md-4 control-label" for="selectbasic">Eu sou</label>
						 		
							</div>
							<div class="row">
						 		<div class="col-md-4">
						 			<select onclick="selectControler()" id="selectbasic" name="selectbasic" class="form-control">
						      		<option name="form-type" onclick="selectControler()" value="1">Freelancer</option>
						      		<option name="form-type" onclick="selectControler()" value="2">Cliente</option>
						   			</select>
						 		</div>
						 		
						</div>
						<div class="row"></div>
						<div class="row">
						 	<div id="sai" class="col-md-4">
					 			<label class="radio-inline" for="radios-0">
					 				<h6 id="pf">Pessoa Física   &nbsp </h6>
					      			<input  name="radios" id="radios-0" value="1" checked="checked" type="radio" onclick="radioControler()">
					     		 
					   			</label> 
					    		<label class="radio-inline" for="radios-1">
					    			<h6 id="pj"> Pessoa Jurídica</h6>
					     		 	<input  name="radios" id="radios-1" value="2" type="radio" onclick="radioControler()">
					      		
					  			 </label>
						 	</div>
						 		
						</div>


						<div class="row">
					 		<label  id="id_nome" class="col-md-4 control-label" for="nome">Nome<h11>*</h11></label>  
					 		<label class="col-md-4 control-label" for="email">Email <h11>*</h11></label>

						</div>
							<div class="row">
						 		<div class="col-md-4">
						 			<input id="nome" name="Nome" placeholder="João marcos Alves" class="form-control input-md" required="" type="text">
						 		</div>

						 		<div class="col-md-4">
						  			<input id="email" name="Email" placeholder="eliot@example.com" class="form-control input-md" required="" type="text">
						  		</div>
						 </div>

						 	<div class="row">
						 		 <label id="cpf" class="col-md-4 control-label" for="cpf">CPF <h11>*</h11> </label> 
						 		 
						 		  <label class="col-md-4 control-label" for="CPF">Senha <h11>*</h11></label>   		
						 	</div>
						 	<div class="row">

							 	<div class="col-md-4">
							 		 <input id="cpf" name="CPF" placeholder="" class="form-control input-md" type="text">
							 	</div>
							 	<div class="col-md-4">
							 	 	<input id="senhaUm" name="Senha" placeholder="" class="form-control input-md" required="" type="password">
							 	</div>
							</div>

							<div class="row">
						 		  
						 		 <label class="col-md-4" id="id_telefone">Telefone <h11>*</h11> </label> 
						 		
						 		  <label class="col-md-4 control-label" for="senhaDois">Confirme a Senha <h11>*</h11></label>     		
						 	</div>
						 	<div class="row">

							 	<div class="col-md-4">
							 		
							 		<input id="tel" name="Telefone" placeholder="8888-8888" class="form-control input-md" required="" type="text">
							 		 
							 	</div>
							 	<div class="col-md-4">
							 	 	 
							 	 	 <input id="senhaDois" name="senhaDois" placeholder="" class="form-control input-md" required="" type="password">
							 	</div>
							</div>

							<div id="group" class="form-group"> 

							<div class="row">
						 		  <label id="id_estado" class="col-md-4 control-label" for="estado">Estado <h11>*</h11> </label>
						 		  <label id="id_banco" class="col-md-4 control-label" for="nome_do_banco">Nome do Banco <h11>*</h11></label>
						 		   		
						 	</div>
						 	<div class="row">

							 	<div class="col-md-4">
							 		 <input id="estado" name="Estado" placeholder="" class="form-control input-md" type="text">

							 	</div>
							 	<div class="col-md-4">
				 						 <select id="nome_do_banco" name="Banco" class="form-control">
									      <option value="BANCO DO BRASIL">BANCO DO BRASIL</option>
									      <option value="CAIXA ECONOMICA">CAIXA ECONOMICA</option>
									      <option value="BRADESCO">BRADESCO</option>
									      <option value="ITAU">ITAU</option>
									      <option value="BANCO DO NORDESTE">BANCO DO NORDESTE</option>
									      <option value="SANTANDE">SANTANDER</option>
									   </select>	 	
				 				</div>
							</div>


							<div class="row">
								<label id="id_cidade" class="col-md-4 control-label" for="cidade">Cidade <h11>*</h11> </label>
								<label id="id_conta" class="col-md-4 control-label" for="conta">Numero da Conta <h11>*</h11></label> 
				      		 	
								   
						 	</div>
						 	<div class="row">

							 	<div class="col-md-4">
							 		<input id="cidade" name="Cidade" placeholder="" class="form-control input-md" required="" type="text">

							 	</div>
							 	<div class="col-md-4">
				 					
				 					
				 					 <input id="conta" name="Conta" placeholder="" class="form-control input-md" required="" type="text">
						 	
				 				</div>
							</div>

							<div class="row">
				      		 	
				      		 	  <label id="id_endereco" class="col-md-4 control-label" for="endereco">Endereço <h11>*</h11></label>
								  <label id="id_agencia" class="col-md-4 control-label" for="agencia">Numero da Agência <h11>*</h11></label>  

						 	</div>
						 	<div class="row">

							 	<div class="col-md-4">
							 		
							 		<input id="endereco" name="Endereco" placeholder="" class="form-control input-md" type="text">
							 	</div>
							 	<div class="col-md-4">
				 					 <input id="agencia" name="Agencia" placeholder="2222-2" class="form-control input-md" required="" type="text">

						 	
				 				</div>
							</div>

							<div class="row">
						  		 <label id="id_sobremim" class="col-md-4 control-label" for="sobre_mim">Sobre Mim</label>
						 		
						 		<label id="id_especialidade" class="col-md-4 control-label" for="especialidade">Especialidade <h11>*</h11></label>   
						 		 

						 	</div>
						 	<div class="row">

							 	<div class="col-md-4">
							 		
							 		 <textarea class="form-control" id="sobre_mim" name="SobreMim">Descrição breve sobre o freelancer</textarea>


							 	</div>
							 	<div class="col-md-4">
							 		<textarea class="form-control" id="especialidade" name="Especialidade">Especialista em Redes Neurais</textarea>	
				 					 

						 	
				 				</div>
							</div>
							</div>

							<div class="row">
								<label class="col-md-4"></label>
						 		  <label class="col-md-4" for="filebutton">Imagem</label>

						 	</div>
						 	<div class="row">
						 		<div class="col-md-4">
				 					<button> Cadastrar </button>
				 					<button> Limpar Dados </button>
				 				</div>

							 	<div class="col-md-4">
				 					  <input id="filebutton" name="Foto" class="input-file" type="file">

						 	
				 				</div>


							</div>
							

						</div>
						  
					
						</div>
					</div>

				</fieldset>
		</form>


	</body>
</html>

mjfreelancer/templates/login/contato.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang='pt-BR'>

	<head>
		<meta charset = "UTF-8"/>
		<title>Majuca Freelancer</title>
		<link rel="stylesheet" href="{% static 'estilos/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'estilos/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'estilos/contato_css.css' %}">
		<script src="{% static 'js/contato.js' %}"></script>	
		

	</head>

	<body>
		<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a  id="mj" class="navbar-brand" style="color: #32CD32"  href="/">Majuca Freelancers</a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">    	
		    </ul>
		 
		  </div>
		 </nav>
 		
		<div id="interface">
			<header id="apresentacao">
				<h3 style="color: rgba(0,0,0,0.7);">Dúvidas e sugestões ?</h3>
				<h3 style="color: rgba(0,0,0,0.7);">Mande uma mensagem para nós.</h3>
			</header>

			<form method="POST" action="" name="cad" onsubmit="return validar()">
			{% csrf_token %}
				<fieldset id="fd1"><legend>Formulário de Contato</legend>
					<p><label for="nome" class="legenda">Nome: </label><br>
						<input id="nome" type="text" name="nome" size="79" placeholder="Informe o seu nome completo" class="campo"></p>
					<p><label for="email" class="legenda">E-mail: </label><br>
						<input type="email" name="Email" id="email" size="79" placeholder="Informe o seu email" class="campo"></p>
	
					<p><label for="data" class="legenda">Data de Nascimento: </label><br>
						<input type="text" name="data" id="data" placeholder="dd/mm/aaaa" class="campo"></p>
					<p><label for="msg" class="legenda">Mensagem: </label><br>
						<textarea class="d"  name="mensagem"  id="msg" cols="80" rows="10" placeholder="Escreva aqui sua mensagem"></textarea></p><br>
					<input type="submit" placeholder="Enviar menssagem" style="position:absolute; right:700px;" class="botao">
					<input type="reset" value="Limpar dados" style="position:relative; right:-390px;" class="botao">
				</fieldset>

			</form>
		</div>
	</body>

</html>

mjfreelancer/templates/login/freelancer.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
<head>
	<title>Freelancer</title>
		<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" href="{% static 'estilos/index.css' %}">
	<link rel="stylesheet" href="{% static 'estilos/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'estilos/bootstrap.min.css' %}">

</head>
	<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a  id="mj" class="navbar-brand" style="color: #32CD32"  href="#">Majuca Freelancers</a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">    	
		    </ul>
		    <div>
		   
		    	</div>

		    <div style="left: -50px" class="dropdown">
		    	 

		    	<a href="#" data-toggle="dropdown"> <img  height="40px" width="40px" src="{% static 'imagens/avatar.png' %}"/> </a>
		    	<b  style="color: white">{{ nome }}</b>
		    	
			 	<span class="caret"></span></button>
			  	<ul style="left: -70px" class="dropdown-menu" >
			  	  
			    <li><a href="#">HTML</a></li>
			    <li><a href="#">CSS</a></li>
			    <li class="divider"></li>
			    <li class="dropdown-header">Configurações</li>
			    <li><a href="#">Sair</a></li>
			  </ul>
		    </div>
		</div>
	</nav>


<body>

</body>
</html>

mjfreelancer/templates/login/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title> Majuca Freelancers</title>
		
		
		<link rel="stylesheet" href="{% static 'estilos/index.css' %}">
		<link rel="stylesheet" href="{% static 'estilos/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'estilos/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'estilos/carousel.css' %}">
		<link rel="stylesheet" href="{% static 'estilos/ie10-viewport-bug-workaround.css' %}">

		
	</head>

	<body>


		<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
		 	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    	<span class="navbar-toggler-icon"></span>
		  	</button>
		  	<a  id="mj" class="navbar-brand" style="color: #32CD32"  href="#">Majuca Freelancers</a>

		  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		    	<ul class="navbar-nav mr-auto">
		      		<li class="nav-item active">
		        		<a class="nav-link" style="color: #32CD32" href="#">Home <span class="sr-only">(current)</span></a>
		      		</li>
		      		
		      		<li class="nav-item">
		        		<a class="nav-link" style="color: #32CD32" href="/contato/">Contato</a>
		      		</li>
		      		
		      		<li class="nav-item">
		       			<a class="nav-link disabled" style="color: #32CD32" href="#">Disabled</a>
		      		</li>
		    	</ul>

	    	
				<div  id="myDropdown" class="dropdown" style="width: 100px">
					<a  id="ex" href="#" class="dropdown-toggle" data-toggle="dropdown"><b> <img height="35px" width="35px" src="{% static 'imagens/login.jpg' %}"/> </b> <span class="caret"></span></a>
					
					<ul id="login-dp" class="dropdown-menu">
						<li>
					 		<div class="row">
								<div class="col-md-12">
									Login via
									<div class="social-buttons">
										<a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i>Facebook</a>
										<a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i>Twitter</a>
									</div>
                                	ou
								 	<form  class="form" role="form" method="post" action="" accept-charset="UTF-8" id="login-nav">
								 	{% csrf_token %}

										<div class="form-group">
											 <label>Email</label>
											 <input type="email" class="form-control" style="width: 205px" name="login_email" placeholder="Email" required>
										</div>
										<div class="form-group">
											 <label>Senha</label>
											 <input id="foca" type="password" class="form-control" style="width: 205px" name="login_senha"  required>
                                             <div class="help-block text-right"><a href="">Esqueceu a senha ?</a></div>
										</div>
										<div class="form-group">
											 <button   id="btsend" type="submit" style="width: 100px" class="btn-login">Entrar</button>
											 	<p id = "retorno" style="color: red" inv="{{ title }}">{{ title }}</p>
										</div>
										<div class="checkbox">
											 <label>
											 <input type="checkbox"> salvar senha
											 </label>
										</div>
								 </form>
							</div>
								<div class="bottom text-center">
									Novo aqui ? <a href="/cadastro/"><b>Faça o cadastro</b></a>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>

		
		</nav>


		<div style="position: absolute; left: 30%; top: 20%">
			<p style="text-align: justify" >
				<b> 
				 O site Majuca Freelancers tem como objetivo principal intermediar<br> 
					a contratação de freelancers, da área de TI, para trabalhar em <br>
					projetos publicados no site pelos contratantes. O cliente poderá <br>
					criar esses projetos definindo suas necessidades e os freelancers<br>
					interessados poderão se candidatar ao trabalho. Por fim, o cliente <br>
					analisará os freelancers que manifestaram interesse pelo seu projeto,<br>
					podendo assim, contratar o que mais se encaixa na sua proposta.
    	
				</b>
			<p>
		
		</div>

	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>	
	<script src="{% static 'js/home.js' %}"></script>
	
	
	
		

	</body>
</html>